
# https://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.2
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--output-format=full", "--fix", "trrex", "docs"]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.22
    hooks:
      # Update the uv lockfile
      - id: uv-lock
      - id: uv-export
        args: [ "--frozen", "--no-hashes", "--no-emit-project", "--group=docs", "--all-extras", "--output-file=docs/requirements.txt" ]
